# Generated by Django 3.1.5 on 2021-05-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='number',
            field=models.IntegerField(null=True, unique=True, verbose_name='№'),
        ),
    ]
