# Generated by Django 3.1.5 on 2021-05-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_job_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='number',
        ),
    ]
